/** Declaration file generated by dts-gen */

import {OperatorsAliases} from 'sequelize';

declare const database: {
    development: {
        host: string;
        port: number;
        database: string;
        password: string;
        username: string;
        use_env_variable?: string;
        operatorsAliases: OperatorsAliases;
        dialect: 'mysql' | 'postgres' | 'sqlite' | 'mssql' | 'mariadb' | undefined;
    };
    production: {
        host: string;
        port: number;
        database: string;
        password: string;
        username: string;
        use_env_variable?: string;
        operatorsAliases: OperatorsAliases;
        dialect: 'mysql' | 'postgres' | 'sqlite' | 'mssql' | 'mariadb' | undefined;
    };
    test: {
        host: string;
        port: number;
        database: string;
        password: string;
        username: string;
        use_env_variable?: string;
        operatorsAliases: OperatorsAliases;
        dialect: 'mysql' | 'postgres' | 'sqlite' | 'mssql' | 'mariadb' | undefined;
    };
};

export = database;

